# Generated by Django 2.1.3 on 2018-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundPot',
            fields=[
                ('id', models.CharField(default='', max_length=9)),
                ('album', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('language', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=120)),
                ('genre', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('song', models.FileField(blank=True, upload_to='songs')),
            ],
        ),
    ]
