# Generated by Django 2.1.3 on 2018-12-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoundPot', '0003_soundpot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundpot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
