# Generated by Django 2.1.3 on 2018-12-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoundPot', '0006_soundpot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundpot',
            name='user',
        ),
    ]
