Quotes = {
"One good thing about music, when it hits you, you feel no pain.":"Bob Marley",
"Music is love, love is music, music is life, and I love my life. Thank you and good night.":"A. J. McLean",
"Where words fail, music speaks.":"Hans Christian Andersen",
"To me there is no picture so beautiful as smiling, bright-eyed, happy children; no music so sweet as their clear and ringing laughter.":"P. T. Barnum",
"Music is the greatest communication in the world. Even if people don't understand the language that you're singing in, they still know good music when they hear it.":"Lou Rawls",
"If music be the food of love, play on.":"William Shakespeare",
"Music is the movement of sound to reach the soul for the education of its virtue.":"Plato",
"Life is one grand, sweet song, so start the music.":"Ronald Reagan",
"Words make you think a thought. Music makes you feel a feeling. A song makes you feel a thought.":"E. Y. Harburg",
"There is pleasure in the pathless woods, there is rapture in the lonely shore, there is society where none intrudes, by the deep sea, and music in its roar; I love not Man the less, but Nature more.":"Lord Byron",
"Music should strike fire from the heart of man, and bring tears from the eyes of woman.":"Ludwig van Beethoven",
"Music expresses that which cannot be said and on which it is impossible to be silent.":"Victor Hugo",
"Music was my refuge. I could crawl into the space between the notes and curl my back to loneliness.":"Maya Angelou",
"There are two means of refuge from the miseries of life: music and cats.":"Albert Schweitzer",
"Without music, life is a journey through a desert.":"Pat Conroy",
"Music, at its essence, is what gives us memories. And the longer a song has existed in our lives, the more memories we have of it.":"Stevie Wonder",
"The true beauty of music is that it connects people. It carries a message, and we, the musicians, are the messengers.":"Roy Ayers",
"If you are a chef, no matter how good a chef you are, it's not good cooking for yourself; the joy is in cooking for others - it's the same with music.":"will.i.am",
"Music is the mediator between the spiritual and the sensual life.":"Ludwig van Beethoven",
"Music is an expression of individuality; it's how you see the world. All art is, for that matter. You take how you experience the world, interpret it, and send it out there - express it - whether it's sculpture, dance or singing.":"David Sanborn",
"Singing is my passion, my first love and the secret of my energy. Music to me is like finding my inner self, my soul. It gives me a great joy to see audiences enjoying with me. I have given my heart to singing. When I sing, I can feel romance in everything around me.":"Kailash Kher",
"Music can change the world because it can change people.":"Bono",
"Some people ask the secret of our long marriage. We take time to go to a restaurant two times a week. A little candlelight, dinner, soft music and dancing. She goes Tuesdays, I go Fridays.":"Henny Youngman",
"The world's most famous and popular language is music.":"Psy",
"I feel like music can affect you in so many ways. When you hear a song with a happy melody, it can change your mood; it can change your day.":"Kygo",
"The best thing about being a DJ is making people happy. There is nothing like seeing people get up from a table to dance or the expression on their face when they hear a song they love. I also love to educate people on music they have never heard.":"Chelsea Leyland",

}
